-- Pexura stok tutarliligi migrasyonu. Supabase SQL Editor'de bir kez calistirilir.
alter table public.urunler add column if not exists toplam_stok numeric;

update public.urunler u
set toplam_stok = greatest(0, coalesce(u.stok_miktar,0) + coalesce(x.satilan,0) - coalesce(x.iade,0))
from (
  select k.urun_id,
    sum(case when lower(coalesce(f.tip,'satis'))='iade' then 0 else coalesce(k.miktar,0) end) satilan,
    sum(case when lower(coalesce(f.tip,'satis'))='iade' then coalesce(k.miktar,0) else 0 end) iade
  from public.fatura_kalemler k join public.faturalar f on f.id=k.fatura_id group by k.urun_id
) x where x.urun_id=u.id and u.toplam_stok is null;
update public.urunler set toplam_stok=coalesce(stok_miktar,0) where toplam_stok is null;
alter table public.urunler alter column toplam_stok set default 0;

create or replace function public.adjust_stock_transaction(p_product_id uuid,p_mode text,p_quantity numeric,p_reason text,p_note text default null)
returns numeric language plpgsql security invoker set search_path=public as $$
declare v_old numeric; v_new numeric; v_delta numeric;
begin
  if p_mode not in ('giris','cikis','sayim') then raise exception 'Gecersiz stok islem turu'; end if;
  if p_quantity is null or p_quantity<0 then raise exception 'Miktar negatif olamaz'; end if;
  if p_mode<>'sayim' and p_quantity=0 then raise exception 'Miktar sifirdan buyuk olmali'; end if;
  if nullif(btrim(coalesce(p_reason,'')),'') is null then raise exception 'Stok hareketi nedeni zorunludur'; end if;
  select coalesce(stok_miktar,0) into v_old from public.urunler where id=p_product_id for update;
  if not found then raise exception 'Urun bulunamadi'; end if;
  v_new:=case p_mode when 'giris' then v_old+p_quantity when 'cikis' then v_old-p_quantity else p_quantity end;
  if v_new<0 then raise exception 'Stok eksiye dusmez. Mevcut: %, istenen cikis: %',v_old,p_quantity; end if;
  v_delta:=v_new-v_old;
  update public.urunler set stok_miktar=v_new,toplam_stok=greatest(0,coalesce(toplam_stok,v_old)+v_delta) where id=p_product_id;
  insert into public.stok_hareketleri(urun_id,miktar_degisim,tur,kaynak,kaynak_id,aciklama,user_id)
  values(p_product_id,v_delta,p_mode,'manuel',p_product_id,concat(p_reason,case when nullif(btrim(coalesce(p_note,'')),'') is not null then ' - '||btrim(p_note) else '' end),auth.uid());
  return v_new;
end; $$;

create or replace function public.batch_adjust_stock_transaction(p_items jsonb,p_reason text,p_note text default null)
returns jsonb language plpgsql security invoker set search_path=public as $$
declare v_item jsonb; v_results jsonb:='[]'::jsonb; v_stock numeric;
begin
  if jsonb_typeof(p_items)<>'array' or jsonb_array_length(p_items)=0 then raise exception 'Stok satiri bulunamadi'; end if;
  for v_item in select value from jsonb_array_elements(p_items) loop
    v_stock:=public.adjust_stock_transaction((v_item->>'product_id')::uuid,v_item->>'mode',(v_item->>'quantity')::numeric,p_reason,p_note);
    v_results:=v_results||jsonb_build_object('product_id',v_item->>'product_id','new_stock',v_stock);
  end loop;
  return v_results;
end; $$;

grant execute on function public.adjust_stock_transaction(uuid,text,numeric,text,text) to authenticated;
grant execute on function public.batch_adjust_stock_transaction(jsonb,text,text) to authenticated;

create table if not exists public.app_error_logs(
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(), user_id uuid, area text not null,
  message text not null, context jsonb
);
alter table public.app_error_logs enable row level security;
drop policy if exists app_error_insert_auth on public.app_error_logs;
create policy app_error_insert_auth on public.app_error_logs for insert to authenticated with check(auth.uid()=user_id);
drop policy if exists app_error_admin_read on public.app_error_logs;
create policy app_error_admin_read on public.app_error_logs for select to authenticated using(true);

create table if not exists public.inventory_daily_snapshots(
  snapshot_date date not null, product_id uuid not null references public.urunler(id) on delete cascade,
  stock_quantity numeric not null, unit_cost numeric not null, currency text not null,
  stock_value numeric not null, created_at timestamptz not null default now(),
  primary key(snapshot_date,product_id)
);
create or replace function public.take_inventory_snapshot() returns integer language plpgsql security definer set search_path=public as $$
declare n integer;
begin
  insert into public.inventory_daily_snapshots(snapshot_date,product_id,stock_quantity,unit_cost,currency,stock_value)
  select current_date,id,coalesce(stok_miktar,0),coalesce(alis_fiyat,0),coalesce(para_birimi,'USD'),round(coalesce(stok_miktar,0)*coalesce(alis_fiyat,0),2) from public.urunler
  on conflict(snapshot_date,product_id) do update set stock_quantity=excluded.stock_quantity,unit_cost=excluded.unit_cost,currency=excluded.currency,stock_value=excluded.stock_value,created_at=now();
  get diagnostics n=row_count; return n;
end; $$;

create extension if not exists pg_cron with schema pg_catalog;
do $$ begin
  if not exists(select 1 from cron.job where jobname='pexura-daily-inventory-snapshot') then
    perform cron.schedule('pexura-daily-inventory-snapshot','5 0 * * *','select public.take_inventory_snapshot();');
  end if;
end $$;

create or replace function public.delete_invoice_transaction(p_invoice_id uuid) returns boolean language plpgsql security invoker set search_path=public as $$
declare v_tip text; r record; v_delta numeric; v_new numeric;
begin
  select lower(coalesce(tip,'satis')) into v_tip from public.faturalar where id=p_invoice_id for update;
  if not found then raise exception 'Fatura bulunamadi'; end if;
  for r in select * from public.fatura_kalemler where fatura_id=p_invoice_id loop
    v_delta:=case when v_tip='iade' then -coalesce(r.miktar,0) else coalesce(r.miktar,0) end;
    update public.urunler set stok_miktar=coalesce(stok_miktar,0)+v_delta where id=r.urun_id returning stok_miktar into v_new;
    if v_new<0 then raise exception 'Fatura silme stogu eksiye dusuruyor'; end if;
    insert into public.stok_hareketleri(urun_id,miktar_degisim,tur,kaynak,kaynak_id,aciklama,user_id)
    values(r.urun_id,v_delta,'silme','fatura',p_invoice_id,'Fatura silindi geri alım',auth.uid());
  end loop;
  delete from public.fatura_kalemler where fatura_id=p_invoice_id;
  delete from public.faturalar where id=p_invoice_id;
  return true;
end; $$;
grant execute on function public.delete_invoice_transaction(uuid) to authenticated;
